### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by hakim-asrori** [startsheep/Administrator-Griya-Jambudipa#5]
# Development (develop)
Branch yang aktif digunakan selama masa pengembangan. Branch ini berisi gabungan dari branch 'feature'

> # Notes
- Branch 'develop' dibuat untuk tahapan development
- Hanya Tech Leader / Reviewer yang diperbolehkan melakukan merge ke branch 'develop'
- Tech Leader / Reviewer memastikan semua kode sesuai dengan standard yang beraku

**Comment by naneps** [comment]
noted
